### PR TITLE
Fix: Make `union_relations` `include/exclude` case insensitive

### LINKED ISSUE #578: `union_relations` `exclude` param not actually excluding
### Describe the bug
The `exclude` param in the `union_relations` function doesn't actually exclude the column from the final result.

### Steps to reproduce
1. Create 2 sources:

```sql
create or replace table development.dbt_jyeo.my_source_a as (
  select 1 as user_id, 'alice' as user_name, 'active' as status
);

create or replace table development.dbt_jyeo.my_source_b as (
  select 2 as user_id, 'bob' as user_name
);
```

2. Add those sources to your project:

```yaml
version: 2
sources:
  - name: dbt_jyeo
    tables:
      - name: my_source_a
      - name: my_source_b
```

3. Add to `dbt_utils` to `package.yml` and then do `dbt deps`.

5. Use `union_relations` in a model and specify `exclude`:

```sql
-- models/my_model.sql
{{ 
  dbt_utils.union_relations(
    relations=[
      source('dbt_jyeo', 'my_source_a'), 
      source('dbt_jyeo', 'my_source_b')
    ],
    exclude=['status']
  ) 
}}
```

6. Run or compile the model above.

7. Check logs or query the table to see that `status` column is not excluded as expected.

### Expected results
Expected that the `status` column is not added to `my_model` table.

### Actual results
`status` column shows up in `my_model` table.

### Screenshots and log output
image

debug logs:

```
2022-05-09T22:29:37.055722Z: 22:29:37  Using snowflake connection "model.my_dbt_project.my_model"
2022-05-09T22:29:37.055847Z: 22:29:37  On model.my_dbt_project.my_model: /* {"app": "dbt", "dbt_version": "1.0.6", "profile_name": "user", "target_name": "default", "node_id": "model.my_dbt_project.my_model"} */


      create or replace transient table development.dbt_jyeo.my_model  as
      (

        (
            select

                cast('development.dbt_jyeo.my_source_a' as 
    varchar
) as _dbt_source_relation,
                
                    cast("USER_ID" as NUMBER(1,0)) as "USER_ID" ,
                    cast("USER_NAME" as character varying(5)) as "USER_NAME" ,
                    cast("STATUS" as character varying(6)) as "STATUS" 

            from development.dbt_jyeo.my_source_a
        )

        union all
        

        (
            select

                cast('development.dbt_jyeo.my_source_b' as 
    varchar
) as _dbt_source_relation,
                
                    cast("USER_ID" as NUMBER(1,0)) as "USER_ID" ,
                    cast("USER_NAME" as character varying(5)) as "USER_NAME" ,
                    cast(null as character varying(6)) as "STATUS" 

            from development.dbt_jyeo.my_source_b
        )

        
      );
2022-05-09T22:29:37.765446Z: 22:29:37  SQL status: SUCCESS 1 in 0.71 seconds
```

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.4
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.0.6 in Cloud
```

### Additional context
Haven't tried to find out why this is happening yet - just reproducing.

### Are you interested in contributing the fix?
Yes

### PR DESCRIPTION
**Pull request by jeremyyeo**
This is a:
- [ ] documentation update
- [x] bug fix with no breaking changes
- [ ] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation
Fixes #578.

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [x] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [ ] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
    - [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [ ] using `dbt_utils.type_*` macros instead of explicit datatypes (e.g. `dbt_utils.type_timestamp()` instead of `TIMESTAMP`
- [ ] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Comment by jeremyyeo** [comment]
@dbeatty10, added your suggested test but I tweaked it a little to actually include upper/lowercase in the `exclude` param... wasn't sure if the test previously would have had that or not 😁

File: integration_tests/models/sql/test_union_exclude_lowercase.sql [hunk 1]
```diff
@@ -0,0 +1,4 @@
+select
+    {{ dbt_utils.star(ref("test_union_exclude_base_lowercase"), except=["_dbt_source_relation"]) }}
```
Comment (joellabes) [inline integration_tests/models/sql/test_union_exclude_lowercase.sql:2]: As of #624 and #661, you can pass `none` into `source_column_name` to suppress the column from being created, if you'd rather.

**Comment by joellabes** [comment]
@jeremyyeo I'm going to merge this into the v1 branch, if (in a separate PR) you wanted to change the integration test to exclude the source column it'd make things slightly tidier, but I won't hold this up for that!
