### PR TITLE
return default in get_column_values if no execute

### LINKED ISSUE #304: get_column_values should return default if not executing
### Describe the bug
I think get_column_values should return default if not executing.
The issue I'm describing is that this function has a `default` parameter that will be returned if no data is found. But if DBT is not on execution mode, it will return an empty string
https://github.com/fishtown-analytics/dbt-utils/blob/c8389533cc7f00823c50d08d904cdfa5f714ec8b/macros/sql/get_column_values.sql#L17

### Steps to reproduce
The easiest way I can think of showing the issue is having a model using this function and surrogate_key. We actually use surrogate_key to calculate a row hash, not really a surrogate key, but the example should work anyway
```
{% set rep_types = dbt_utils.get_column_values(source_table, 'rep_type', default=[]) %}
...
{{ dbt_utils.surrogate_key(columns) }} AS row_hash
```

### Expected results
I would expect it to return `[]` as that's defined as the default value in my code

### Actual results
It's returning an empty string instead `''`

### Screenshots and log output
```
Running with dbt=0.18.1

Warning: the `surrogate_key` macro now takes a single list argument instead of multiple string arguments. Support for multiple string arguments will be deprecated in a future release of dbt-utils. The slice.advertiser_rep_assignment_current model triggered this warning.
```

### System information
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: [">=0.6.0", "<0.7.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - redshift: 0.18.1
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - postgres: 0.18.1
```

### Additional context
https://github.com/fishtown-analytics/dbt-utils/blob/c8389533cc7f00823c50d08d904cdfa5f714ec8b/macros/sql/get_column_values.sql#L17

### Are you interested in contributing the fix?
I can't do this now but I'm getting my company to agree on the CLA

### PR DESCRIPTION
**Pull request by jmriego**
This is a:
- [x] bug fix PR with no breaking changes — please ensure the base branch is `master`
- [ ] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
Fixes #304 
I think get_column_values should return default if not executing.
The issue I'm describing is that this function has a default parameter that will be returned if no data is found. But if DBT is not on execution mode, it will return an empty string
https://github.com/fishtown-analytics/dbt-utils/blob/c8389533cc7f00823c50d08d904cdfa5f714ec8b/macros/sql/get_column_values.sql#L17

Using this simple code will trigger a warning as columns will default to an empty string if no execute:
```
{% set rep_types = dbt_utils.get_column_values(source_table, 'rep_type', default=[]) %}
{{ dbt_utils.surrogate_key(columns) }} AS row_hash
```

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [x] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [x] I have "dispatched" any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

### CODE REVIEW

File: macros/sql/get_column_values.sql [hunk 1]
```diff
@@ -6,7 +6,7 @@
```
Comment (jasnonaz) [inline macros/sql/get_column_values.sql:6]:
``` suggestion 
{% if default is none %}
    {% set default = [] %}
{% endif %}
```

**Comment by jasnonaz** [comment]
This looks great!! Just adding one additional bit of logic as in the case someone doesn't specify default, we'd want to return an empty list rather than none.

**Review by joellabes — APPROVED** [review]
Thanks for the contribution @jmriego!
