### PR TITLE
Change from quotes to backticks for BQ

### LINKED ISSUE #536: BQ get_relations_by_pattern gives `Unexpected string literal "table_type"` error
### Describe the bug
[From the community Slack](https://getdbt.slack.com/archives/CMZ2V0X8V/p1649381252167749)
image
 

### Expected results
Not to get an error

### Actual results
An error `Unexpected string literal "table_type"`

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt Cloud 1.0
```

### Additional context
This is my fault - https://github.com/dbt-labs/dbt-utils/pull/525 changed this, and the original author called out that quoting the column caused this error. Unfortunately, at the last moment I re-quoted it to avoid a Snowflake issue (https://github.com/dbt-labs/dbt-utils/issues/484#issuecomment-1089274595)

This can be handled by creating a BQ-specific override that _doesn't_ quote the resulting column. 

### Are you interested in contributing the fix?
Extremely

### PR DESCRIPTION
**Pull request by joellabes**
This is a:
- [x] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [ ] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
Resolves #536 

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [x] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake

### CODE REVIEW

File: macros/sql/get_table_types_sql.sql [hunk 1]
```diff
@@ -20,3 +20,12 @@
...
             end as "table_type"
 {% endmacro %}
+
+{% macro bigquery__get_table_types_sql() %}
+            case table_type
+                when 'BASE TABLE' then 'table'
+                when 'EXTERNAL TABLE' then 'external'
+                when 'MATERIALIZED VIEW' then 'materializedview'
+                else lower(table_type)
+            end as `table_type`
```
Comment (jtcohen6) [inline macros/sql/get_table_types_sql.sql:30]: You can use `adapter.quote()` here (source: core/default](https://github.com/dbt-labs/dbt-core/blob/899b0ef2241d97d97df5270c20b67be02ec7ca61/core/dbt/adapters/sql/impl.py#L202-L203), [dbt-bigquery](https://github.com/dbt-labs/dbt-bigquery/blob/edebc4728fe6fc6cac79d853387060142e7b9e06/dbt/adapters/bigquery/impl.py#L311-L313))
